// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanGenerator.Templates.E2eTests
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class E2eTestsTemplate : E2eTestsTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using ");
            
            #line 6 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".E2eTests.Shared.Dtos.");
            
            #line 6 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("s;\r\nusing ");
            
            #line 7 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".E2eTests.Shared.Endpoints;\r\nusing ");
            
            #line 8 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".E2eTests.Shared.Extensions;\r\nusing ");
            
            #line 9 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".E2eTests.Shared.WebApplicationFactory;\r\nusing FluentAssertions;\r\nusing Xunit.Abs" +
                    "tractions;\r\n\r\nnamespace ");
            
            #line 13 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".E2eTests.");
            
            #line 13 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("s;\r\n\r\n[Collection(CustomWebApplicationCollection.Name)]\r\npublic class ");
            
            #line 16 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("E2eTests : TestBase\r\n{\r\n    public ");
            
            #line 18 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("E2eTests(\r\n        CustomWebApplicationFixture webApplicationFixture,\r\n        IT" +
                    "estOutputHelper testOutputHelper) :\r\n        base(webApplicationFixture, testOut" +
                    "putHelper)\r\n    {\r\n    }\r\n\r\n    [Fact]\r\n    public async Task ShouldReturnCreate" +
                    "d");
            
            #line 26 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("ById()\r\n    {\r\n        var createResponse = await HttpClient.Create");
            
            #line 28 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("().Call(new() {\r\n");
            
            #line 29 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    foreach(var propertyConfig in _model.PropertyConfigs)
    {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 33 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 33 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.TestValue(0)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 34 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        });\r\n\r\n        await createResponse.Should().HaveStatusCode(201);\r\n\r\n    " +
                    "    var created");
            
            #line 41 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("Id = await createResponse.ReadResponseContentAs<int>();\r\n\r\n        var get");
            
            #line 43 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("ByIdResponse = await HttpClient.Get");
            
            #line 43 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("ById().Call(created");
            
            #line 43 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("Id);\r\n\r\n        await get");
            
            #line 45 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("ByIdResponse.Should().HaveStatusCode(200);\r\n\r\n        var returned");
            
            #line 47 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write(" = await get");
            
            #line 47 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("ByIdResponse.ReadResponseContentAs<");
            
            #line 47 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("Dto>();\r\n\r\n");
            
            #line 49 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    foreach(var propertyConfig in _model.PropertyConfigs)
    {

            
            #line default
            #line hidden
            this.Write("        returned");
            
            #line 53 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 53 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.Name));
            
            #line default
            #line hidden
            this.Write(".Should().Be(");
            
            #line 53 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.TestValue(0)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 54 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    [Fact]\r\n    public async Task ShouldListCreated");
            
            #line 60 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("s()\r\n    {\r\n        var ");
            
            #line 62 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("1Id = await HttpClient.Create");
            
            #line 62 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("().CallAndParseResponse(new() {\r\n");
            
            #line 63 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    foreach(var propertyConfig in _model.PropertyConfigs)
    {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 67 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 67 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.TestValue(0)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 68 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        });\r\n        var ");
            
            #line 72 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("2Id = await HttpClient.Create");
            
            #line 72 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("().CallAndParseResponse(new() {\r\n");
            
            #line 73 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    foreach(var propertyConfig in _model.PropertyConfigs)
    {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 77 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 77 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.TestValue(1)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 78 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        });\r\n\r\n        var list");
            
            #line 83 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("sResult = await HttpClient.List");
            
            #line 83 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("s().CallAndParseResponse(new()\r\n        {\r\n            PageIndex = 1,\r\n          " +
                    "  PageSize = 5,\r\n        });\r\n\r\n        list");
            
            #line 89 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("sResult.Items.Should().HaveCount(2);\r\n        list");
            
            #line 90 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("sResult.Items[0].Should().BeEquivalentTo(new ");
            
            #line 90 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("Dto() {\r\n            Id = ");
            
            #line 91 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("1Id,\r\n");
            
            #line 92 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    foreach(var propertyConfig in _model.PropertyConfigs)
    {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 96 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 96 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.TestValue(0)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 97 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        });\r\n        list");
            
            #line 101 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("sResult.Items[1].Id.Should().Be(");
            
            #line 101 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("2Id);\r\n    }\r\n\r\n    [Fact]\r\n    public async Task ShouldUpdate");
            
            #line 105 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("()\r\n    {\r\n        var ");
            
            #line 107 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("Id = await HttpClient.Create");
            
            #line 107 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("().CallAndParseResponse(new() {\r\n");
            
            #line 108 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    foreach(var propertyConfig in _model.PropertyConfigs)
    {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 112 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 112 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.TestValue(0)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 113 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        });\r\n\r\n        var updateResponse = await HttpClient.Update");
            
            #line 118 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("().Call(new() {\r\n            Id = ");
            
            #line 119 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("Id,\r\n");
            
            #line 120 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    foreach(var propertyConfig in _model.PropertyConfigs)
    {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 124 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 124 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.UpdatedTestValue(0)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 125 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        });\r\n\r\n        await updateResponse.Should().HaveStatusCode(200);\r\n\r\n    " +
                    "    var updated");
            
            #line 132 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write(" = await HttpClient.Get");
            
            #line 132 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("ById().CallAndParseResponse(");
            
            #line 132 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("Id);\r\n\r\n        updated");
            
            #line 134 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write(".Should().BeEquivalentTo(new ");
            
            #line 134 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("Dto() {\r\n            Id = ");
            
            #line 135 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("Id,\r\n");
            
            #line 136 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    foreach(var propertyConfig in _model.PropertyConfigs)
    {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 140 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 140 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.UpdatedTestValue(0)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 141 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        });\r\n    }\r\n\r\n    [Fact]\r\n    public async Task ShouldDelete");
            
            #line 148 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("()\r\n    {\r\n        var ");
            
            #line 150 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("Id1 = await HttpClient.Create");
            
            #line 150 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("().CallAndParseResponse(new() {\r\n");
            
            #line 151 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    foreach(var propertyConfig in _model.PropertyConfigs)
    {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 155 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 155 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.TestValue(0)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 156 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        });\r\n        var ");
            
            #line 160 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("Id2 = await HttpClient.Create");
            
            #line 160 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("().CallAndParseResponse(new() {\r\n");
            
            #line 161 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    foreach(var propertyConfig in _model.PropertyConfigs)
    {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 165 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 165 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyConfig.TestValue(1)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 166 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("        });\r\n\r\n        var delete");
            
            #line 171 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("Response = await HttpClient.Delete");
            
            #line 171 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("().Call(");
            
            #line 171 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("Id1);\r\n\r\n        await delete");
            
            #line 173 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("Response.Should().HaveStatusCode(200);\r\n\r\n        var list");
            
            #line 175 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("sResult = await HttpClient.List");
            
            #line 175 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("s().CallAndParseResponse(new()\r\n        {\r\n            PageIndex = 1,\r\n          " +
                    "  PageSize = 5,\r\n        });\r\n\r\n        list");
            
            #line 181 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("sResult.Items.Should().HaveCount(1);\r\n        list");
            
            #line 182 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("sResult.Items[0].Id.Should().Be(");
            
            #line 182 "C:\Users\JonoTassia\source\ClearSkyLogic\CleanGenerator\CleanGenerator\Templates\E2eTests\E2eTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityVariableName));
            
            #line default
            #line hidden
            this.Write("Id2);\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class E2eTestsTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
